### ISSUE TITLE
'Zend_Log' not found?

### ISSUE THREAD

**Issue by gavie** [MtGox/magento#5]
Hi, I installed this plugin, but got the following error upon going to my shopping cart:

Fatal error: Class 'Zend_Log' not found in /usr/home/xxxxxx/domains/xxxxxxxxxxxxxxx/public_html/app/code/local/Mtgox/Bitcoin/Model/Bitcoin.php on line 196

Any solutions?

**Comment by MagicalTux** [comment]
That's weird, line 196 of https://github.com/MtGox/magento/blob/master/app/code/community/Mtgox/Bitcoin/Model/Bitcoin.php is the last line, and that file includes no call to Zend_Log.

Could you confirm the version of Magento you're using so we can try and see if we can reproduce this problem?

**Comment by gavie** [comment]
Thanks for your reply. We use version 1.6.2.0
Your help is veery much appreciated. We really want to try this extension.
Great work!

**Comment by gavie** [comment]
It happens as soon as something is added to the cart:

https://www.xxxxxx.com/onestepcheckout/cart/add/uenc/aHR0cDovL3d3dy50cnVmZmxlbWFnaWMuY29tL3dlYnNob3Av/product/6/

And with onestepcheckout disabled (using the default magento checkout), it happens at the checkout page:

https://www.xxxxxx.com/checkout/onepage/

**Comment by AlexMtGox** [comment]
Hi

We pushed an update on this Magento Module, could you please check if your issue is resolved or not?

Thanks

**Comment by MetaH** [comment]
Hi

I am also having the same fatal error issue as per follows:

Upon clicking on the PROCEED TO CHECKOUT button, I have the following FATAL ERROR on my server: 

Fatal error: Class 'Zend_Log' not found in public_html/app/code/community/Mtgox/Bitcoin/Model/Bitcoin.php on line 196 

Please note that MERCHANT ID, API KEY and API SECRET KEY has been correctly entered and Bitcoin payment module enabled.

Magento Version currently used is : 1.5

Thank you for responding at earliest convenience.

**Comment by gavie** [comment]
Unfortunately the update did not fix it for me.

**Comment by MetaH** [comment]
Guys please find updated version as follows:

https://github.com/MtGox/magento

Go through the application and you should be able to make it functional...Cheers

**Comment by artmechanix** [comment]
I'm also experiencing this issue with Magento version 1.7.0.2.  I have 1. installed all of the latest GitHub files manually  2. used Magento Connect to install from Magento Extensions and 3. tried overwriting Magento Connect files with the GitHub ones.  The installation still returns the Fatal error, regarding the Zend_Log class, mentioned above.  It happens at Checkout.

**Comment by MetaH** [comment]
Only a developper from Tibanne can assist us.. latest news I got.. he is on vacation and in a week's time, he should be around.. so lets be patient and see how we can best implement this payment module.. Cheers and God Bless ; )

**Comment by MetaH** [comment]
Hiya.. any update please over the MTGOX payment integration ? Thank you for responding dear developers.. Cheers: )

**Comment by jgautheron** [comment]
Hi! I'm back from vacations... I'm currently looking at it, expect a fix in the two next days.

**Comment by MetaH** [comment]
Hi Jonathan
Welcome back.. This is a great relief.
Thank you for investigating over the matter.
Just to summarize: The MTGOX payment module for Magento leaves a bug on the checkout page.
As such, once this is checked and resolved, kindly do provide an update.
I did observe there are some few guys on the GITHUB facing more or less the same problem.
Thanks once again and big cheers : MetaH : )
Date: Thu, 6 Sep 2012 11:44:36 -0700
Subject: Re: [magento] 'Zend_Log' not found? (#5)

Hi! I'm back from vacations... I'm currently looking at it, expect a fix in the two next days.

```
          —

          Reply to this email directly or view it on GitHub.
```

**Comment by jgautheron** [comment]
The update has been pushed to Magento Connect, version 1.0.5.

**How to install properly**

1- Uninstall the module
2- Clear your Magento cache
3- Install the extension

Let me know how that works out for you.

**Comment by MetaH** [comment]
Hi Jonathan

Thanks for the update, much appreciated.

However, I am having the invalid API settings upon enabling the module.

What should be done in such a case? Thanks for the response.

Cheers

**Comment by jgautheron** [comment]
Try save it again!

**Comment by MetaH** [comment]
Thats weird.. still getting same status after updating my API key: The MtGox payment module has been disabled since the API settings are invalid.

**Comment by jgautheron** [comment]
If you are sure that your key and secret are correct, try after this notice shows up to Enable the module again and save the configuration.

**Comment by MetaH** [comment]
ok KOOL.. I have created a new api key where a new secret key is generated.. and so it has been saved correctly and enabled.. again KOOL ; ) 

And also, good news, checkout is appearing GOOD .. real GOOD without FATAL error.. 

SUPERB.. i repeat again.. SUPERB

Big cheers Jonathan.. you are the best.. Keep it up and thumbs up ^_^
